name: MLOps Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - uses: actions/checkout@v3

    # 2. Set up Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    # 4. Run Tests
    - name: Run Tests with Pytest
      run: pytest

    # 5. Build Docker Image (to ensure Dockerfile is valid)
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag flight-price-api:latest